### ISSUE TITLE
Passing a class as a value in an ActiveRecord query

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/rails_deprecation_log_analyser#5]
Build a classifier to classify the following:

Passing a class as a value in an Active Record query is deprecated and will be removed. Pass a string instead. (called from find_or_initialize_by at /var/lib/jenkins/gems/ruby/2.3.0/gems/protected_attributes_continued-1.3.0/lib/active_record/mass_assignment_security/relation.rb:53)

**Comment by mrwinton** [comment]
Branch `class_arguement_in_active_record_query_classifier` ready for review.
