### ISSUE TITLE
Comparing equality between `ActionController::Parameters` and a `Hash`

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/rails_deprecation_log_analyser#6]
Build a classifier to classify the following:

Comparing equality between `ActionController::Parameters` and a `Hash` is deprecated and will be removed in Rails 5.1. Please only do comparisons between instances of `ActionController::Parameters`. If you need to compare to a hash, first convert it using `ActionController::Parameters#new`. (called from == at /var/lib/jenkins/gems/ruby/2.3.0/gems/rspec-expectations-3.5.0/lib/rspec/matchers/built_in/eq.rb:35)

**Comment by mrwinton** [comment]
Branch `equality_comparison_between_parameters_and_hash` ready for review.

**Comment by randomcodenz** [comment]
Reviewed - see comment in the pull request. Is a hard one though as I don't know how we can label the deprecation warning.

**Comment by mrwinton** [comment]
Yeah, naming is hard :)

I've updated the deprecation title to "Parameters and Hash comparison" I think once you have looked at one of the deprecations warnings it'll be easy to recall what this title is referring to.

Do you think it's sufficient?
