### ISSUE TITLE
:restrict_dependent_destroy.many

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/rails_deprecation_log_analyser#7]
Build a classifier to classify the following:

The error key `:'restrict_dependent_destroy.many'` has been deprecated and will be removed in Rails 5.1. Please use `:'restrict_dependent_destroy.has_many'` instead. (called from block in transaction_with_isolation_level at /var/lib/jenkins/gems/ruby/2.3.0/gems/transaction_isolation_level-1.1.0/lib/transaction_isolation_level/adapter_patches.rb:43)

**Comment by mrwinton** [comment]
Branch `restrict_dependent_destroy_classifier` ready for review.
