### ISSUE TITLE
Returning `false` in Active Record and Active Model callbacks

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/rails_deprecation_log_analyser#8]
Build a classifier to classify the following:

Returning `false` in Active Record and Active Model callbacks will not implicitly halt a callback chain in Rails 5.1. To explicitly halt the callback chain, please use `throw :abort` instead. (called from block in transaction_with_isolation_level at /var/lib/jenkins/gems/ruby/2.3.0/gems/transaction_isolation_level-1.1.0/lib/transaction_isolation_level/adapter_patches.rb:43)

**Comment by mrwinton** [comment]
Branch `implicit_callback_chain_escape` ready for review.
