### ISSUE TITLE
redirect_to :back

### ISSUE THREAD

**Issue by randomcodenz** [randomcodenz/rails_deprecation_log_analyser#9]
Build a classifier to classify the following:

`redirect_to :back` is deprecated and will be removed from Rails 5.1. Please use `redirect_back(fallback_location: fallback_location)` where `fallback_location` represents the location to use if the request has no HTTP referer information. (called from destroy at /var/lib/jenkins/powershop/app/controllers/admin/consumers_controller.rb:209)

**Comment by mrwinton** [comment]
Branch `redirect_to_back` ready for review.
